add_test( [==[Registry: register and unregister sender]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: register and unregister sender]==]  )
set_tests_properties( [==[Registry: register and unregister sender]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Registry: register multiple senders]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: register multiple senders]==]  )
set_tests_properties( [==[Registry: register multiple senders]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Registry: unregister non-existent sender]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: unregister non-existent sender]==]  )
set_tests_properties( [==[Registry: unregister non-existent sender]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Registry: open sender state]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: open sender state]==]  )
set_tests_properties( [==[Registry: open sender state]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Registry: open non-existent sender state]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: open non-existent sender state]==]  )
set_tests_properties( [==[Registry: open non-existent sender state]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Registry: register with null arguments]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: register with null arguments]==]  )
set_tests_properties( [==[Registry: register with null arguments]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Registry: cleanup stale entries does not crash]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Registry: cleanup stale entries does not crash]==]  )
set_tests_properties( [==[Registry: cleanup stale entries does not crash]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Discovery: empty directory]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Discovery: empty directory]==]  )
set_tests_properties( [==[Discovery: empty directory]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Discovery: find registered sender]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Discovery: find registered sender]==]  )
set_tests_properties( [==[Discovery: find registered sender]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Discovery: multiple senders]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Discovery: multiple senders]==]  )
set_tests_properties( [==[Discovery: multiple senders]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
add_test( [==[Discovery: enumerate returns correct backend type]==] /Users/2bit/prog/cpp/nozzle/build-nozzle/tests/nozzle_tests [==[Discovery: enumerate returns correct backend type]==]  )
set_tests_properties( [==[Discovery: enumerate returns correct backend type]==] PROPERTIES WORKING_DIRECTORY /Users/2bit/prog/cpp/nozzle/build-nozzle/tests)
set( nozzle_tests_TESTS [==[Registry: register and unregister sender]==] [==[Registry: register multiple senders]==] [==[Registry: unregister non-existent sender]==] [==[Registry: open sender state]==] [==[Registry: open non-existent sender state]==] [==[Registry: register with null arguments]==] [==[Registry: cleanup stale entries does not crash]==] [==[Discovery: empty directory]==] [==[Discovery: find registered sender]==] [==[Discovery: multiple senders]==] [==[Discovery: enumerate returns correct backend type]==])
